### ISSUE TITLE
Updating to 0.1.3

### ISSUE THREAD

**Issue by ahuhn** [yedpodtrzitko/mypy-nonfloat-decimal#1]
This looks great! I went to fix the Union thing and realized that it's already fixed. I was wondering how to update https://pypi.org/project/mypy-nonfloat-decimal/ with the most recent version. (It's still at 0.1.2)

Thanks!
Anika

**Comment by yedpodtrzitko** [comment]
I'll see what I can do :)

**Comment by yedpodtrzitko** [comment]
@ahuhn give it a try (it's `0.1.4` though)

**Comment by ahuhn** [comment]
Thank you so much! I thought it would just be an upload and not any code updates, but I have updated my internal mental model of how pypi gets updated, and I read up on how to do it myself in the future. Thanks again!
